name: Hello First Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # ← lets you run it manually too

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Greet everyone
        run: echo "Hello Dost!"

      - name: Show current user
        run: echo "Hello $USER"
